create TABLE alert (
    id BIGINT Not NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    sent TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;