spring.application.name= insight-service

server.port=8085

# =========================================================
# Actuator & Prometheus 
# =========================================================

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}

usage.service.url=http://localhost:8083/api/v1/usage

# =========================================================
# Spring AI Configuration for NVIDIA NIM (GLM model)
# =========================================================

spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1

spring.ai.openai.api-key=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

spring.ai.openai.chat.model=z-ai/glm-5.3

spring.ai.openai.chat.temperature=0.5
spring.ai.openai.chat.top-p=1.0
spring.ai.openai.chat.max-tokens=1024
spring.ai.openai.chat.options.timeout=30s

logging.level.org.springframework.ai=DEBUG
logging.level.web=DEBUG

spring.resilience4j.retry.instances.aiCall.register-health-indicator=true
spring.resilience4j.retry.instances.aiCall.max-attempts=3
spring.resilience4j.retry.instances.aiCall.wait-duration=2s
spring.resilience4j.retry.instances.aiCall.retry-exceptions=org.springframework.ai.retry.NonTransientAiException,org.springframework.web.reactive.function.client.WebClientResponseException,java.util.concurrent.TimeoutException

spring.resilience4j.circuitbreaker.instances.aiCall.register-health-indicator=true
spring.resilience4j.circuitbreaker.instances.aiCall.sliding-window-size=10
spring.resilience4j.circuitbreaker.instances.aiCall.minimum-number-of-calls=5
spring.resilience4j.circuitbreaker.instances.aiCall.failure-rate-threshold=50
spring.resilience4j.circuitbreaker.instances.aiCall.wait-duration-in-open-state=30s
spring.resilience4j.circuitbreaker.instances.aiCall.permitted-number-of-calls-in-half-open-state=3